"""Render client-native governance surfaces from the canonical rule corpus."""

from __future__ import annotations

import hashlib
import json
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

import yaml

from kt_scaffold.corpus import corpus_digest, load_rules
from kt_scaffold.models import Answers, Change, Rule, RuleScope
from kt_scaffold.safety import atomic_write, safe_join
from kt_scaffold.technology import load_technology_profile

BANNER_MD = "<!-- GENERATED by kt-scaffold. Edit rules/, then render. -->"
BANNER_TOML = "# GENERATED by kt-scaffold. Edit rules/, then render."


@dataclass(frozen=True)
class CommandSpec:
    name: str
    cli: str
    description: str
    arguments: str


COMMANDS = (
    CommandSpec(
        "project_init",
        "init",
        "Create one complete project transactionally.",
        "--target-dir, --intent, --primary-domain and profile answers",
    ),
    CommandSpec(
        "scaffold_update",
        "update",
        "Bring untouched generated files forward and report conflicts.",
        "--target-dir and optional answer overrides",
    ),
    CommandSpec(
        "rules_list",
        "rules",
        "List applicable rules without loading every body.",
        "--scope, --path or --trigger",
    ),
    CommandSpec(
        "rules_get", "rule", "Read selected canonical rule bodies.", "one or more rule IDs"
    ),
    CommandSpec(
        "clients_render",
        "render",
        "Render or check client-native governance files.",
        "--target-dir and --mode",
    ),
    CommandSpec(
        "spec_new",
        "spec",
        "Create a roadmap-linked capability PRD.",
        "--domain, --capability, --intent and --mode",
    ),
    CommandSpec(
        "backend_domain_new",
        "domain",
        "Generate a backend vertical from an accepted PRD.",
        "--spec-path and authorization options",
    ),
    CommandSpec(
        "frontend_page_new",
        "page",
        "Generate a localized frontend page from an accepted PRD.",
        "--spec-path, --page and --route",
    ),
    CommandSpec(
        "schema_change_prepare",
        "schema",
        "Prepare a profile-native migration from an accepted PRD.",
        "--spec-path, --summary and --migration-name",
    ),
    CommandSpec(
        "quality_gate",
        "gate",
        "Execute locally or prepare/finalize content-bound remote quality evidence.",
        "phase, scope, optional browser evidence, and explicit project-code trust "
        "for local execute",
    ),
    CommandSpec(
        "browser_scenario_new",
        "scenario",
        "Create and register a browser scenario from an accepted PRD.",
        "--spec-path, --suite, --title and acceptance points",
    ),
    CommandSpec(
        "done_report",
        "done",
        "Compare a claimed evidence tier with recorded evidence.",
        "--change-summary and --claimed-tier",
    ),
)

TURKISH_COMMANDS = {
    "init": (
        "baslat",
        "Projeyi tek ve işlemsel bir adımda oluştur.",
        "hedef dizin, amaç, ana alan ve profil yanıtları",
    ),
    "update": (
        "guncelle",
        "Yerel proje iskeleti güncellemesini çatışmaları koruyarak uygula.",
        "hedef dizin ve isteğe bağlı yanıt değişiklikleri",
    ),
    "rules": (
        "kurallar",
        "İlgili kuralların gövdelerini yüklemeden listesini getir.",
        "kapsam, yol veya tetikleyici",
    ),
    "rule": (
        "kural",
        "Seçilen kanonik kural gövdelerini oku.",
        "bir veya daha fazla kural kimliği",
    ),
    "render": (
        "yansit",
        "Ajan istemcilerine özgü yönetişim dosyalarını üret veya doğrula.",
        "hedef dizin ve çalışma modu",
    ),
    "spec": (
        "spesifikasyon",
        "Yol haritasına bağlı yetenek PRD'si oluştur.",
        "alan, yetenek, amaç ve ayrıntı modu",
    ),
    "domain": (
        "alan",
        "Kabul edilmiş PRD'den dikey bir arka uç dilimi üret.",
        "PRD yolu ve yetkilendirme seçenekleri",
    ),
    "page": (
        "sayfa",
        "Kabul edilmiş PRD'den yerelleştirilmiş bir ön yüz sayfası üret.",
        "PRD yolu, sayfa ve rota",
    ),
    "schema": (
        "sema",
        "Kabul edilmiş PRD için teknoloji profiline özgü migrasyon hazırlığını yap.",
        "PRD yolu, değişiklik özeti ve migrasyon adı",
    ),
    "gate": (
        "kalite-kapisi",
        "Yerel kalite kapısını çalıştır veya kanıt akışını hazırla.",
        "aşama, kapsam, tarayıcı kanıtı ve yerel kod çalıştırma onayı",
    ),
    "scenario": (
        "senaryo",
        "Kabul edilmiş PRD'den kalıcı bir tarayıcı senaryosu oluştur.",
        "PRD yolu, test paketi, başlık ve kabul maddeleri",
    ),
    "done": (
        "tamamla",
        "İddia edilen kanıt seviyesini kayıtlı kanıtla karşılaştır.",
        "değişiklik özeti ve iddia edilen seviye",
    ),
}

COMMAND_SCOPES: dict[str, RuleScope] = {
    "init": "process",
    "update": "governance",
    "rules": "governance",
    "rule": "governance",
    "render": "governance",
    "spec": "process",
    "domain": "backend",
    "page": "frontend",
    "schema": "schema",
    "gate": "quality",
    "scenario": "quality",
    "done": "quality",
}

TURKISH_REPORT_GUIDANCE = """\
# Sabit koşum raporu

Her test paketi, tarayıcı geçişi, doğrulama taraması, senaryo grubu veya ürünün kendi
üzerinde denenmesi sonrasında aşağıdaki yapıyı kullan. 1–3. bölümler zorunludur ve bu sırayı
korur. 4. bölüm yalnızca okuyucudan açık sorular üzerinde karar vermesi istendiğinde eklenir.

```markdown
# Koşum raporu — <YYYY-AA-GG> · <kapsam, tek cümle>

1. Sonuç: <tek cümlelik hüküm> — birim N başarılı / tarayıcı M başarılı / atlanan K;
   karar bekleyen: J (M3, M6) veya karar bekleyen: yok.
2. Koşulan: <test paketi -> dosya -> sayı satırları veya kısa bir tablo; ortamı belirt>.
3. Maddeler:
   **KUSUR**
   M1 ... (DÜZELTİLDİ, dosya/test)
   **TUZAK**
   M2 ...
   M3 ... ← KARAR
   **GÖZLEM** — yok
   **AÇIK**
   M4 ...
   **YAN-ETKİ**
   M5 ...
4. Açık sorular: S1..Sn
```

Beş grubun anlamı:

| Etiket | İçerik |
|---|---|
| `KUSUR` | Bulunan kusur, düzeltilmiş olsa da olmasa da, koruyucu dosya/test bilgisiyle |
| `TUZAK` | Sonraki bir koşumun aynı işi yinelemeden önce bilmesi gereken davranış |
| `GÖZLEM` | Bilerek değiştirilmemiş kanıt ve kaydedildiği yer |
| `AÇIK` | Kapsanmayan durum ve nedeni |
| `YAN-ETKİ` | Koşumu mümkün kılmak için yapılan depo, yapılandırma veya fikstür değişikliği |

Değişmeyen dokuz kural:

1. 1–3. bölümler her zaman sırasıyla bulunur; boş değer atlanmaz, `— yok` yazılır.
2. `M1..Mn` numaraları beş grup boyunca kesintisiz ilerler ve yeniden başlamaz.
3. Beş grup etiketi belirtilen sırayla yer alır; boş gruplar da gösterilir ve altıncı grup eklenmez.
4. Okuyucu kararı gerektiren madde `← KARAR` ile biter; 1. bölüm sayı ve madde numaralarını verir.
5. 1. bölüm gözlenen başarılı/atlanan sayılarını içerir; sayısız tamamlanma ifadesi geçersizdir.
6. Grup içinde önem derecesine göre sırala ve karar gerektiren maddeleri önce yaz.
7. Bir maddeyi bir, en fazla iki satırda tut; ayrıntılı çıktıyı metne gömmek yerine bağla.
8. Koşum için yapılan fikstür veya veri değişikliği yeni bölüm değil, yan etkidir.
9. Açıklama dili rapor dilini izler; yapısal etiketler eksiksiz Türkçe kümeden gelir.

Tam bir eşleme varsa yapılandırılmış ana dili kullan; yoksa kanonik İngilizceye dön. Kısmi çeviri
uydurma. Tamamlama raporu işlemi yalnızca öneri niteliğindedir; yine de bu biçimi korumalı ve
kanıtlanmamış iddiaları sessizce düşürmek yerine numaralı açık/kusur maddeleri olarak göstermelidir.
"""


def _rule_markdown(rule: Rule) -> str:
    return f"## {rule.title}\n\n{rule.body.strip()}\n"


def _policy_anchors(root: Path) -> list[str]:
    profile = load_technology_profile(root / "technology-profile.yml")
    answers_payload = yaml.safe_load(
        (root / ".kt-scaffold/answers.yml").read_text(encoding="utf-8")
    )
    answers = Answers.model_validate(answers_payload)
    forbidden = ", ".join(profile.forbidden)
    return [
        f"- `technology-profile.yml#profile_id` = `{profile.profile_id}`",
        (
            "- `technology-profile.yml#application_modes.default` = "
            f"`{profile.application_modes.default}`"
        ),
        f"- `technology-profile.yml#backend.language` = `{profile.backend.language}`",
        f"- `technology-profile.yml#backend.framework` = `{profile.backend.framework}`",
        f"- `technology-profile.yml#backend.alternatives` = `{profile.backend.alternatives}`",
        f"- `technology-profile.yml#frontend.framework` = `{profile.frontend.framework}`",
        f"- `technology-profile.yml#frontend.build` = `{profile.frontend.build}`",
        f"- `technology-profile.yml#frontend.rendering` = `{profile.frontend.rendering}`",
        f"- `technology-profile.yml#persistence.engine` = `{profile.persistence.engine}`",
        f"- `technology-profile.yml#persistence.orm` = `{profile.persistence.orm}`",
        f"- `technology-profile.yml#persistence.migrations` = `{profile.persistence.migrations}`",
        (
            "- `technology-profile.yml#persistence.vector.extension` = "
            f"`{profile.persistence.vector.extension}`"
        ),
        (
            "- `technology-profile.yml#persistence.vector.status` = "
            f"`{profile.persistence.vector.status}`"
        ),
        (
            "- `technology-profile.yml#embeddings.generation_boundary` = "
            f"`{profile.embeddings.generation_boundary}`"
        ),
        (f"- `technology-profile.yml#embeddings.provider` = `{profile.embeddings.provider}`"),
        (
            "- `technology-profile.yml#architecture.server_side_rendering` = "
            f"`{profile.architecture.server_side_rendering}`"
        ),
        f"- `technology-profile.yml#architecture.nextjs` = `{profile.architecture.nextjs}`",
        f"- `technology-profile.yml#forbidden` = `[{forbidden}]`",
        f"- `.kt-scaffold/answers.yml#backend_profile` = `{answers.backend_profile}`",
        (f"- `.kt-scaffold/answers.yml#persistence_profile` = `{answers.persistence_profile}`"),
    ]


def _agents(rules: Iterable[Rule], policy_anchors: Iterable[str]) -> str:
    rules = list(rules)
    always = [rule for rule in rules if rule.trigger == "always"]
    scoped = [rule for rule in rules if rule.trigger == "path-match"]
    lines = [
        BANNER_MD,
        "# Agent contract",
        "",
        "This repository is spec-first and offline-first. The rules below are authoritative.",
        "Path-scoped details are projected into each client's native rule mechanism.",
        "The global MCP supplies governance intent only; local agents own all edits and tests.",
        "Mandatory behaviors may be reworded or strengthened but never weakened.",
        "",
        "## Machine-derived policy anchors",
        "",
        "These values are rendered from the local authorities; do not replace them with memory,",
        "invented alternatives, or line-number citations.",
        "",
        *policy_anchors,
        "",
    ]
    for rule in always:
        lines.extend([_rule_markdown(rule), ""])
    lines.extend(["## Path-scoped rule index", ""])
    for rule in scoped:
        lines.append(f"- {rule.id}: {rule.title} — {', '.join(rule.applies_to)}")
    lines.extend(["", "## Commands", ""])
    for command in COMMANDS:
        lines.append(f"- /kt-{command.cli}: {command.description}")
        alias, description, _arguments = TURKISH_COMMANDS[command.cli]
        lines.append(f"- /kt-{alias}: {description} (Türkçe eşlenik)")
    return "\n".join(lines).rstrip() + "\n"


def _claude() -> str:
    return (
        f"{BANNER_MD}\n"
        "# Claude Code\n\n"
        "@AGENTS.md\n\n"
        "Use the bank-managed kt-scaffold MCP server over stdio or\n"
        "Streamable HTTP for deterministic initial scaffolding, blueprint and governance "
        "knowledge.\n"
        "Never upload workspace contents.\n"
        "Apply initial bundle bytes mechanically; reconcile later update intents\n"
        "against the local copy, preserve mandatory behaviors, record decisions, then use local\n"
        "filesystem and execution tools. The /kt-* skills may use the optional local CLI.\n"
    )


def _path_rule(rule: Rule, client: str) -> str:
    if client == "claude":
        paths = "\n".join(f"  - {item}" for item in rule.applies_to)
        front = f"---\npaths:\n{paths}\n---\n"
    else:
        globs = ", ".join(rule.applies_to)
        front = f"---\ndescription: {rule.title}\nglobs: {globs}\nalwaysApply: false\n---\n"
    return f"{BANNER_MD}\n{front}\n# {rule.title}\n\n{rule.body}"


def render_skill(command: CommandSpec, *, language: str = "en") -> str:
    if language == "tr":
        cli, description, arguments = TURKISH_COMMANDS[command.cli]
        equivalent = f"kt-{command.cli}"
        usage = f"/kt-{cli} çağrıldığında veya kullanıcı bu işlemi Türkçe istediğinde kullan."
        details = (
            f"Argümanlar: {arguments}.\n\n"
            f"Birebir eşleniği: /{equivalent}. İki ad da aynı yerel işlemi çağırır.\n\n"
            "Bu bir yerel uygulayıcı işlemidir: geçerli çalışma alanını yerel ajan araçlarıyla "
            "inceleyip düzenle veya isteğe bağlı komut satırı aracı kuruluysa eşdeğer "
            "argümanlarla "
            f"kt-scaffold {command.cli} çalıştır. İlke bağlamı için merkezi MCP yönetişim "
            "kataloğunu kullan; MCP'den dosya sistemi değişikliği bekleme. Zorunlu davranışları "
            "koru; çatışmaları, uyarıları ve eksik kanıtları bildir.\n"
        )
    else:
        cli, description, arguments = command.cli, command.description, command.arguments
        equivalent = f"kt-{TURKISH_COMMANDS[command.cli][0]}"
        usage = f"Use when the user invokes /kt-{cli} or asks for this scaffold operation."
        details = (
            f"Arguments: {arguments}.\n\n"
            f"Exact equivalent: /{equivalent}. Both names invoke the same local operation.\n\n"
            "This is a trusted-local operation: inspect and edit the current workspace with "
            "local agent tools, or run kt-scaffold "
            f"{command.cli} with equivalent arguments when the optional CLI is installed. Use "
            "the global MCP governance catalog for policy context, not for filesystem mutation. "
            "Preserve mandatory behaviors and report conflicts, warnings and missing evidence.\n"
        )
    skill_name = f"kt-{cli}"
    return (
        "---\n"
        f"name: {skill_name}\n"
        f"description: {description} {usage}\n"
        "---\n\n"
        f"{BANNER_MD}\n"
        f"# /kt-{cli}\n\n"
        f"{description}\n\n"
        f"{details}"
    )


def _report_skill(rule: Rule, locale: str) -> str:
    if locale.startswith("tr"):
        description = (
            "Bir test paketi, tarayıcı, doğrulama, senaryo veya ürünün kendi üzerinde denenmesi "
            "koşumunu sabit kanıt raporu biçiminde yaz."
        )
        heading = "Test koşumu raporu"
        instruction = "Türkçe etiket kümesini kullan."
        guidance = TURKISH_REPORT_GUIDANCE
    else:
        description = (
            "Format a test-suite, browser, verification, scenario or dogfooding run using the "
            "fixed evidence report."
        )
        heading = "Test run report"
        instruction = "Use the canonical English label set."
        guidance = rule.body
    return (
        "---\n"
        "name: kt-test-run-report\n"
        f"description: {description}\n"
        "---\n\n"
        f"{BANNER_MD}\n"
        f"# {heading}\n\n{instruction}\n\n{guidance}"
    )


def expected_client_files(root: Path, rules: list[Rule], primary_locale: str) -> dict[str, bytes]:
    files: dict[str, str] = {
        "AGENTS.md": _agents(rules, _policy_anchors(root)),
        "CLAUDE.md": _claude(),
        ".claude/settings.json": json.dumps({"enableAllProjectMcpServers": False}, indent=2) + "\n",
        ".codex/config.toml": (
            f"{BANNER_TOML}\n"
            "# The bank manages the global stdio or Streamable HTTP MCP registration; this "
            "project declares none.\n"
        ),
    }
    for rule in rules:
        if rule.trigger == "path-match":
            files[f".claude/rules/{rule.id}.md"] = _path_rule(rule, "claude")
            files[f".cursor/rules/{rule.id}.mdc"] = _path_rule(rule, "cursor")
    for command in COMMANDS:
        for language, cli in (("en", command.cli), ("tr", TURKISH_COMMANDS[command.cli][0])):
            body = render_skill(command, language=language)
            files[f".claude/skills/kt-{cli}/SKILL.md"] = body
            files[f".codex/skills/kt-{cli}/SKILL.md"] = body
    report_rule = next((item for item in rules if item.id.startswith("53-")), None)
    if report_rule:
        body = _report_skill(report_rule, primary_locale)
        files[".claude/skills/kt-test-run-report/SKILL.md"] = body
        files[".codex/skills/kt-test-run-report/SKILL.md"] = body
    always = [rule for rule in rules if rule.trigger == "always"]
    files[".specify/memory/constitution.md"] = (
        f"{BANNER_MD}\n# Project constitution\n\n"
        + "\n\n".join(_rule_markdown(rule).strip() for rule in always)
        + "\n"
    )
    return {path: content.encode("utf-8") for path, content in files.items()}


def render_clients(
    root: str | Path,
    *,
    mode: str = "write",
    clients: list[str] | None = None,
    primary_locale: str = "en",
) -> tuple[list[Change], list[dict[str, str]]]:
    if mode not in {"write", "check"}:
        raise ValueError("mode must be write or check")
    project_root = Path(root).resolve(strict=True)
    rules_dir = project_root / "rules"
    rules = load_rules(rules_dir)
    all_expected = expected_client_files(project_root, rules, primary_locale)
    selected_prefixes = {
        "agents": ("AGENTS.md",),
        "claude": ("CLAUDE.md", ".claude/"),
        "codex": (".codex/",),
        "cursor": (".cursor/",),
        "spec-kit": (".specify/",),
    }
    selected = set(clients or selected_prefixes)
    unknown = sorted(selected - set(selected_prefixes))
    if unknown:
        raise ValueError(f"unknown governance clients: {', '.join(unknown)}")

    def owned_by_selected_client(relative: str) -> bool:
        return any(
            relative.startswith(prefix)
            for client in selected
            for prefix in selected_prefixes[client]
        )

    expected = {path: data for path, data in all_expected.items() if owned_by_selected_client(path)}

    changes: list[Change] = []
    drift: list[dict[str, str]] = []
    for relative, content in sorted(expected.items()):
        destination = safe_join(project_root, relative)
        if not destination.exists():
            changes.append(Change(path=relative, action="create"))
            drift.append({"path": relative, "reason": "missing"})
            if mode == "write":
                atomic_write(project_root, relative, content)
            continue
        current = destination.read_bytes()
        if current == content:
            changes.append(Change(path=relative, action="skip"))
            continue
        changes.append(Change(path=relative, action="update"))
        drift.append({"path": relative, "reason": "content differs"})
        if mode == "write":
            atomic_write(project_root, relative, content)

    if mode == "write":
        lock = {
            "corpus_digest": corpus_digest(rules_dir),
            "files": {
                path: hashlib.sha256(data).hexdigest()
                for path, data in sorted(all_expected.items())
            },
        }
        atomic_write(
            project_root,
            "rules/GENERATED.lock",
            (json.dumps(lock, indent=2, sort_keys=True) + "\n").encode(),
        )
    return changes, drift
