apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.modelStorage.claimName }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.modelStorage.className | quote }}
  resources:
    requests: {storage: {{ .Values.modelStorage.size }}}
