apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.audioStorage.claimName }}
spec:
  accessModes: [{{ .Values.audioStorage.accessMode }}]
  storageClassName: {{ .Values.audioStorage.className | quote }}
  resources:
    requests: {storage: {{ .Values.audioStorage.size }}}
