apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {app.kubernetes.io/part-of: "voiceup", app.kubernetes.io/component: backend}
spec:
  type: ClusterIP
  selector: {app.kubernetes.io/part-of: "voiceup", app.kubernetes.io/component: backend}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}

