apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {app.kubernetes.io/part-of: "@@PRODUCT_SLUG@@", app.kubernetes.io/component: frontend}
spec:
  type: ClusterIP
  selector: {app.kubernetes.io/part-of: "@@PRODUCT_SLUG@@", app.kubernetes.io/component: frontend}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}

