"""meeting_profile_population

Revision ID: 9cf5f2d22daf
Revises: f43fd9e32042
Create Date: 2026-09-11 05:20:16.314324
"""

from collections.abc import Sequence

from alembic import op
from pgvector.sqlalchemy import VECTOR
import sqlalchemy as sa

revision: str = "9cf5f2d22daf"
down_revision: str | None = "f43fd9e32042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "speaker_profile",
        sa.Column(
            "meeting_embedding",
            VECTOR(dim=256),
            nullable=True,
            comment="Separate normalized Community embedding component for verified meeting memory; never scored with ECAPA.",
        ),
    )
    op.add_column(
        "speaker_profile",
        sa.Column(
            "meeting_model_id",
            sa.String(length=120),
            nullable=True,
            comment="Immutable package identity of the optional meeting embedding component.",
        ),
    )
    op.add_column(
        "speaker_profile",
        sa.Column(
            "meeting_model_revision",
            sa.String(length=64),
            nullable=True,
            comment="Immutable revision of the separate 256-dimensional meeting population.",
        ),
    )
    op.add_column(
        "speaker_profile",
        sa.Column(
            "meeting_preprocessing_version",
            sa.String(length=64),
            nullable=True,
            comment="Versioned meeting quality and final retained-audio preprocessing lineage.",
        ),
    )
    op.add_column(
        "speaker_profile",
        sa.Column(
            "meeting_source_sha256",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 of the exact retained PCM WAV used for the meeting memory vectors.",
        ),
    )
    op.add_column(
        "speaker_profile",
        sa.Column(
            "meeting_recording_id",
            sa.BigInteger(),
            nullable=True,
            comment="Same-tenant retained source recording for this optional immutable meeting template.",
        ),
    )
    op.create_foreign_key(
        "fk_speaker_profile_meeting_recording",
        "speaker_profile",
        "recording",
        ["tenant_id", "meeting_recording_id"],
        ["tenant_id", "recording_id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_speaker_profile_speaker_profile_meeting_population"),
        "speaker_profile",
        "(meeting_embedding IS NULL AND meeting_model_id IS NULL AND meeting_model_revision IS NULL AND meeting_preprocessing_version IS NULL AND meeting_source_sha256 IS NULL AND meeting_recording_id IS NULL) OR (meeting_embedding IS NOT NULL AND meeting_model_id IS NOT NULL AND meeting_model_revision IS NOT NULL AND meeting_preprocessing_version IS NOT NULL AND meeting_source_sha256 IS NOT NULL AND meeting_recording_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_speaker_profile_speaker_profile_meeting_population"),
        "speaker_profile",
        type_="check",
    )
    op.drop_constraint(
        "fk_speaker_profile_meeting_recording", "speaker_profile", type_="foreignkey"
    )
    op.drop_column("speaker_profile", "meeting_recording_id")
    op.drop_column("speaker_profile", "meeting_source_sha256")
    op.drop_column("speaker_profile", "meeting_preprocessing_version")
    op.drop_column("speaker_profile", "meeting_model_revision")
    op.drop_column("speaker_profile", "meeting_model_id")
    op.drop_column("speaker_profile", "meeting_embedding")
    # ### end Alembic commands ###
