"""Shared conservative projection policy for client adapters."""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from typing import ClassVar, Literal

import yaml

from kt_scaffold.agent_platform.models import (
    CanonicalAgentPackage,
    ExternalControl,
    MappedField,
    RenderedProjection,
    SemanticLoss,
)

SAFETY_ENVELOPE = """# Projection safety envelope

- Read and search project files only; never write or change state.
- Do not access the network or use web, MCP, command, execution, test, or scanner capabilities.
- Do not spawn, invoke, or delegate to child agents.
- Return advisory evidence only; this projection grants no runtime authority.
"""

EXTERNAL_CONTROLS = (
    ExternalControl(
        id="inference-admission",
        statement=(
            "Resolve and admit the provider, model, endpoint, and inference profile outside "
            "the repository."
        ),
    ),
    ExternalControl(
        id="identity-secret-dlp",
        statement=(
            "Broker identity and credentials and enforce secret handling and data-loss "
            "prevention externally."
        ),
    ),
    ExternalControl(
        id="sandbox-egress",
        statement=(
            "Enforce effective filesystem sandboxing and network egress outside this agent file."
        ),
    ),
    ExternalControl(
        id="tool-mcp-admission",
        statement="Admit tools and MCP servers through a provenance-pinned external registry.",
    ),
    ExternalControl(
        id="side-effect-approval",
        statement="Require an external approval boundary for privileged or side-effecting actions.",
    ),
    ExternalControl(
        id="delivery-admission",
        statement=(
            "Keep CI rulesets, signing, release, and deployment admission outside the agent "
            "runtime."
        ),
    ),
)


def yaml_scalar(value: str) -> str:
    """JSON strings are deterministic valid YAML scalars."""

    return json.dumps(value, ensure_ascii=False)


def yaml_frontmatter(fields: tuple[tuple[str, object], ...], body: str) -> str:
    lines = ["---"]
    for key, value in fields:
        if isinstance(value, bool):
            lines.append(f"{key}: {'true' if value else 'false'}")
        elif isinstance(value, int):
            lines.append(f"{key}: {value}")
        elif isinstance(value, str):
            lines.append(f"{key}: {yaml_scalar(value)}")
        elif isinstance(value, tuple):
            lines.append(f"{key}:")
            lines.extend(f"  - {yaml_scalar(str(item))}" for item in value)
        else:
            raise TypeError(f"unsupported frontmatter value for {key}")
    return "\n".join((*lines, "---", body.rstrip(), ""))


def parse_yaml_frontmatter(content: str) -> tuple[dict[str, object], str]:
    if not content.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")
    parts = content.split("\n---\n", 1)
    if len(parts) != 2:
        raise ValueError("unterminated YAML frontmatter")
    value = yaml.safe_load(parts[0][4:])
    if not isinstance(value, dict):
        raise ValueError("YAML frontmatter must be a mapping")
    return value, parts[1]


class ProjectionAdapter(ABC):
    """Pure adapter. Implementations render and parse-check one client surface."""

    client_id: ClassVar[str]
    adapter_id: ClassVar[str]
    adapter_version: ClassVar[str] = "1.0.1"
    media_type: ClassVar[Literal["text/markdown", "application/toml"]]
    allowed_fields: ClassVar[frozenset[str]]

    @abstractmethod
    def relative_path(self, agent_id: str) -> str:
        raise NotImplementedError

    @abstractmethod
    def render(self, package: CanonicalAgentPackage) -> RenderedProjection:
        raise NotImplementedError

    @abstractmethod
    def validate(self, content: str, package: CanonicalAgentPackage) -> tuple[str, ...]:
        raise NotImplementedError

    def projected_description(self, package: CanonicalAgentPackage) -> str:
        if package.agent_id == "test-automation":
            return (
                "Designs bounded tests and reviews supplied evidence; this projection cannot "
                "execute tests."
            )
        return package.description

    def body(self, package: CanonicalAgentPackage) -> str:
        return (
            "<!-- Generated by the governed projection compiler; inert until separately "
            "activated. -->\n\n"
            f"{SAFETY_ENVELOPE}\n"
            "# Canonical instructions\n\n"
            f"{package.instructions.strip()}\n"
        )

    def base_mappings(self) -> tuple[MappedField, ...]:
        return (
            MappedField(canonical="metadata.id", projected_to=("name",)),
            MappedField(canonical="metadata.description", projected_to=("description",)),
            MappedField(canonical="mission.instructions_ref", projected_to=("body",)),
        )

    def base_losses(self, package: CanonicalAgentPackage) -> tuple[SemanticLoss, ...]:
        losses = [
            SemanticLoss(
                code="AP_LOSS_REGISTRY_REFS_EXTERNAL",
                canonical="requirements.inference_profile_ref|policies|rules|skills|commands",
                disposition="external-control",
                statement=(
                    "Canonical registry references are not embedded and require trusted "
                    "external resolution."
                ),
            ),
            SemanticLoss(
                code="AP_LOSS_HOOKS_EXTERNAL",
                canonical="requirements.hook_intents",
                disposition="external-control",
                statement=(
                    "Required lifecycle intents are not emitted as command hooks and require "
                    "external enforcement and audit."
                ),
            ),
            SemanticLoss(
                code="AP_LOSS_INTERFACE_SCHEMA_EXTERNAL",
                canonical="interfaces",
                disposition="external-control",
                statement="Input and output schemas are not enforced by the custom-agent file.",
            ),
            SemanticLoss(
                code="AP_LOSS_DENY_GLOBS_EXTERNAL",
                canonical="permissions.workspace.deny",
                disposition="external-control",
                statement=(
                    "Workspace deny globs require the effective external sandbox and DLP policy."
                ),
            ),
            SemanticLoss(
                code="AP_LOSS_RUNTIME_AUTHORITY_EXTERNAL",
                canonical="permissions.network|secrets|external_side_effects",
                disposition="external-control",
                statement=(
                    "Network, secret, and external-side-effect denial is requested but not "
                    "proven by repository text."
                ),
            ),
            SemanticLoss(
                code="AP_LOSS_DELEGATION_INSTRUCTION_ONLY",
                canonical="delegation",
                disposition="instruction-only",
                statement=(
                    "Child-agent denial remains instruction-level unless the admitted runtime "
                    "proves enforcement."
                ),
            ),
            SemanticLoss(
                code="AP_LOSS_BUDGETS_EXTERNAL",
                canonical="runtime.budgets",
                disposition="external-control",
                statement="Tool-call and resource budgets require an external runtime control.",
            ),
            SemanticLoss(
                code="AP_LOSS_DATA_EVIDENCE_EXTERNAL",
                canonical="data|evidence",
                disposition="external-control",
                statement=(
                    "Classification, retention, logging, evaluation, and approval evidence "
                    "remain external."
                ),
            ),
            SemanticLoss(
                code="AP_LOSS_MODEL_INHERITED",
                canonical="requirements.inference_profile_ref",
                disposition="inherited",
                statement=(
                    "No provider or model is pinned; effective inference routing is inherited "
                    "and must be admitted separately."
                ),
            ),
        ]
        optional_tools = tuple(
            tool["capability"]
            for tool in package.contract["requirements"]["tools"]
            if not tool["required"]
        )
        if optional_tools:
            losses.append(
                SemanticLoss(
                    code="AP_LOSS_OPTIONAL_TOOLS_OMITTED",
                    canonical="requirements.tools",
                    disposition="omitted",
                    statement=(
                        "Optional execution or observation capabilities are deliberately omitted: "
                        + ", ".join(optional_tools)
                        + "."
                    ),
                )
            )
        return tuple(losses)

    def projection(
        self,
        package: CanonicalAgentPackage,
        *,
        content: str,
        mapped_fields: tuple[MappedField, ...],
        extra_losses: tuple[SemanticLoss, ...] = (),
    ) -> RenderedProjection:
        validations = self.validate(content, package)
        return RenderedProjection(
            content=content,
            mapped_fields=mapped_fields,
            semantic_losses=(*self.base_losses(package), *extra_losses),
            external_controls=EXTERNAL_CONTROLS,
            validations=validations,
        )

    def validate_frontmatter(
        self,
        content: str,
        package: CanonicalAgentPackage,
    ) -> tuple[dict[str, object], str]:
        frontmatter, body = parse_yaml_frontmatter(content)
        unknown = set(frontmatter) - self.allowed_fields
        if unknown:
            raise ValueError(f"unsupported or unstable fields emitted: {sorted(unknown)}")
        if frontmatter.get("name") != package.agent_id:
            raise ValueError("projected name does not match canonical agent id")
        if frontmatter.get("description") != self.projected_description(package):
            raise ValueError("projected description does not match selected safe description")
        if package.instructions.strip() not in body:
            raise ValueError("canonical instructions are missing from projection body")
        if "Projection safety envelope" not in body:
            raise ValueError("projection safety envelope is missing")
        return frontmatter, body
