"""Codex custom-agent TOML projection."""

from __future__ import annotations

import json
import re
import tomllib

from kt_scaffold.agent_platform.adapters.base import ProjectionAdapter
from kt_scaffold.agent_platform.models import (
    CanonicalAgentPackage,
    MappedField,
    RenderedProjection,
    SemanticLoss,
)


class CodexAdapter(ProjectionAdapter):
    client_id = "codex"
    adapter_id = "codex"
    adapter_version = "1.0.2"
    media_type = "application/toml"
    allowed_fields = frozenset({"name", "description", "sandbox_mode", "developer_instructions"})

    def body(self, package: CanonicalAgentPackage) -> str:
        return (
            "<!-- Generated by the governed projection compiler; inert until separately "
            "activated. -->\n\n"
            "# Projection safety envelope\n\n"
            "- Read and search project files only; never write or change state.\n"
            "- Use the local shell only for read-only workspace inspection. Use literal, "
            "quoted workspace paths and non-mutating inspection commands.\n"
            "- Never execute project code, scripts, interpreters, package managers, tests, "
            "builds, scanners, redirections, command substitutions, or state-changing "
            "version-control commands.\n"
            "- Do not access denied paths, including .env files and secret directories.\n"
            "- Do not access the network or use web or MCP capabilities.\n"
            "- Do not spawn, invoke, or delegate to child agents.\n"
            "- Return advisory evidence only; this projection grants no runtime authority.\n\n"
            "# Canonical instructions\n\n"
            f"{package.instructions.strip()}\n"
        )

    def relative_path(self, agent_id: str) -> str:
        return f".codex/agents/{agent_id}.toml"

    def render(self, package: CanonicalAgentPackage) -> RenderedProjection:
        instructions = self.body(package)
        description = self.projected_description(package)
        native_name = package.agent_id.replace("-", "_")
        if not re.fullmatch(r"[a-z][a-z0-9_]*", native_name):
            raise ValueError("Codex native agent name cannot be normalized safely")
        content = (
            f"name = {json.dumps(native_name, ensure_ascii=False)}\n"
            f"description = {json.dumps(description, ensure_ascii=False)}\n"
            'sandbox_mode = "read-only"\n'
            f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}\n"
        )
        return self.projection(
            package,
            content=content,
            mapped_fields=(
                *self.base_mappings(),
                MappedField(canonical="runtime.workspace_access", projected_to=("sandbox_mode",)),
                MappedField(
                    canonical="requirements.tools[tool:workspace-read]",
                    projected_to=("sandbox_mode", "developer_instructions"),
                ),
            ),
            extra_losses=(
                SemanticLoss(
                    code="AP_LOSS_CODEX_WORKSPACE_READ_TOOL_INHERITED",
                    canonical="requirements.tools[tool:workspace-read]",
                    disposition="inherited",
                    statement=(
                        "Codex performs local file reads through its shell/tool surface; the "
                        "agent file requests read-only inspection, while effective tool "
                        "availability and parent overrides require runtime evidence."
                    ),
                ),
                SemanticLoss(
                    code="AP_LOSS_PARENT_OVERRIDE_INHERITED",
                    canonical="runtime.sandbox_required",
                    disposition="inherited",
                    statement=(
                        "A live parent configuration may supersede the agent sandbox default "
                        "and requires effective-config capture."
                    ),
                ),
            ),
        )

    def validate(self, content: str, package: CanonicalAgentPackage) -> tuple[str, ...]:
        value = tomllib.loads(content)
        if set(value) != self.allowed_fields:
            raise ValueError("Codex projection contains unsupported or missing fields")
        if (
            value["name"] != package.agent_id.replace("-", "_")
            or value["sandbox_mode"] != "read-only"
        ):
            raise ValueError("Codex projection violates id or read-only sandbox invariant")
        if package.instructions.strip() not in value["developer_instructions"]:
            raise ValueError("Codex projection lost canonical instructions")
        if (
            "Use the local shell only for read-only workspace inspection."
            not in value["developer_instructions"]
            or "Never execute project code" not in value["developer_instructions"]
        ):
            raise ValueError("Codex projection lost the bounded workspace-read mapping")
        return (
            "tomllib-parse",
            "stable-field-allowlist",
            "native-name-normalized",
            "read-only-sandbox",
            "bounded-workspace-read",
            "instructions-present",
        )
